trigger:
- main

jobs:
- job: AndroidBuild
  displayName: 'Build for Android'
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'
  
  - script: npm install
    displayName: 'Install dependencies'
  
  - script: npm test
    displayName: 'Run tests'
  
  - script: |
      npx react-native run-android --variant=release
    displayName: 'Build Android app'
    condition: and(succeeded(), eq(variables['Build.Platform'], 'Android'))

- job: iOSBuild
  displayName: 'Build for iOS'
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js on macOS'
  
  - script: npm install
    displayName: 'Install dependencies on macOS'
  
  - script: npm test
    displayName: 'Run tests on macOS'
  
  - script: |
      npx react-native run-ios --configuration Release
    displayName: 'Build iOS app'
    condition: and(succeeded(), eq(variables['Build.Platform'], 'iOS'))
