trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

# Install dependencies
- script: npm install
  displayName: 'Install dependencies'

# Run tests
- script: npm test
  displayName: 'Run tests'

# Conditional step for Android build (Can run on Windows)
- script: |
    npx react-native run-android --variant=release
  displayName: 'Build Android app'
  condition: and(succeeded(), eq(variables['Build.Platform'], 'Android'))

# Placeholder for iOS build (Requires macOS agent)
- script: echo "Placeholder for iOS build step. Requires macOS agent."
  displayName: 'iOS Build Placeholder'
  condition: and(succeeded(), eq(variables['Build.Platform'], 'iOS'))

# Additional steps for deployment or further actions can be added here
jobs:
- job: AndroidBuild
  pool:
    vmImage: 'windows-latest'
  steps:
    # Steps for Android build (similar to above)

- job: iOSBuild
  pool:
    vmImage: 'macOS-latest'
  steps:
    # Steps for iOS build, e.g., installing dependencies, running tests, building the iOS app
